version: '2'
services:
  app:
    container_name: cryptopro
    build:
      context: .
      args:
        - PUBLIC_KEY_FILE_NAME=${PUBLIC_KEY_FILE_NAME}
        - PRIVATE_KEY_FOLDER_NAME=${PRIVATE_KEY_FOLDER_NAME}
    expose:
      - 80
    ports:
      - ${APP_HOST_IP}:${APP_HOST_PORT}:80
#    volumes:
#      - ./www:/var/www/html
